<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\Refund\" />
    <Folder Include="DTOs\Payments\" />
    <Folder Include="Features\Owners\Query\" />
    <Folder Include="Features\Payments\Command\" />
    <Folder Include="Features\Payments\Query\" />
    <Folder Include="Features\Refound\Command\" />
    <Folder Include="Features\Refound\Query\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="2.3.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CaspiEra.Domain\CaspianEra.Domain.csproj" />
  </ItemGroup>

</Project>
